### ISSUE TITLE
Review usage of unstable APIs

### ISSUE THREAD

**Issue by niax** [niax/rust-email#10]
Rust's nightly as of 2015-01-09 has warnings for usage of unstable APIs on by default - showing up APIs that may be going away shortly. It'd be nice to be ahead of the curve for a change. See [the build log for 0.0.7](https://travis-ci.org/niax/rust-email/builds/46508183) for a full list.

- [x] `as_slice`, `slice`, `slice_from`, `slice_to` usages should use slicing syntax or other
- [x] `std::fmt::Show`/`std::fmt::String` is still unstable - awaiting outcome from upstream
- [x] Range notation instead of `range`

**Comment by untitaker** [comment]
I recieve plenty of warnings, but none of those that you mentioned. See #14 for a fix of some of them.

**Comment by untitaker** [comment]
Fixed a long time ago.
